development:
  adapter: postgresql 
  database: chatchit
  username: hungkm
  password: n0
  pool: 5

test:
  adapter: postgresql 
  database: chatchit_test
  username: hungkm
  password: n0
  pool: 5

